### PR TITLE
Sprint 1

### PR DESCRIPTION
**Pull request by LaansDole**

### CODE REVIEW

**Review by Rainb0wBanana — APPROVED** [review]
Very good!

**Comment by Cullen179** [comment]
Nice

**Comment by james-dinhh** [comment]
Nice

**Review by Cullen179 — APPROVED** [review]

**Review by james-dinhh — APPROVED** [review]
nice

**Review by nhatxminh — APPROVED** [review]

**Review by Rainb0wBanana — APPROVED** [review]

**Review by Hankaji — COMMENTED** [review]
Reviewed

**Review by Hankaji — APPROVED** [review]
Reviewed

**Pull request merged**
